### ISSUE TITLE
URL with UUID

### ISSUE THREAD

**Issue by Eeeeelias** [daisybio/DIGGER#41]
In order to improve shareability to the analyses we can add the UUIDs to the url so that anyone with the UUID can see the results.

In addition, we should add a dropdown that enables the user to potentially save the file in the backend for up to 6 months.

**Comment by PelzKo** [comment]
accessing a result with the uuid is possible now. Dropdown and different deletion times will be implemented after meeting

**Comment by PelzKo** [comment]
closed with #52
