### ISSUE TITLE
Display input parameters in results

### ISSUE THREAD

**Issue by PelzKo** [daisybio/DIGGER#71]
Especially when we are sharing results, it might be interesting being able to understand where the results come from. So maybe we could add either a Parameter section which contains the parameters used to create the results or add an info icon which you can hover over to get that information

**Comment by Eeeeelias** [comment]
That is a wonderful idea that I've considered before, but ultimately I couldn't find the right way of displaying these parameters in a UX friendly way. Do you happen to have an idea on how we could display these parameters nicely such that they integrate well with the website? 
I'd love to implement it in that case.

**Comment by PelzKo** [comment]
There are two options in my opinion:
1. Add them into the information table, so after the availability and sharing link
2. Add an information popup (maybe an i in a circle and if you hover over it, it will show the parameters)
(2. This could also be exactly like "Link for sharing:" but "Parameters:" and the button contains an information symbol and when you click on it, you get a pop up or something drops down or whatever)

**Comment by Eeeeelias** [comment]
I would prefer option two, as option one would extend the length of the table quite a bit and move the content of the actual page too far down. Using a modal would be the easiest implementation I suppose.

**Comment by PelzKo** [comment]
I agree. Would you like some more input from me on that? Do you just wanna implement it and I'll give you feedback? Should I implement a first draft? What works best for you?

**Comment by Eeeeelias** [comment]
Feel free to implement a draft, and then we can iterate from there :)

**Comment by PelzKo** [comment]
Implemented a basic version using alert in #88 . This should work, but we need to delete the saved runs because I changed the model (so all the saved runs will not be accessible anymore)
Showing the user the info is very simple and could be remade with a modal or dialog box so it looks nicer
