### ISSUE TITLE
Frequently asked questions (FAQ)

### ISSUE THREAD

**Issue by PelzKo** [daisybio/DIGGER#86]
We can collect faqs here in this issue.

**Comment by PelzKo** [comment]
What is the difference between SE.MATS.JC.txt and SE.MATS.JCEC.txt when using rMATS. Which one should I choose?

Answer: See [documentation](https://github.com/Xinglab/rmats-turbo?tab=readme-ov-file#output). Both work with nease. _Do we recommend something?_

**Comment by OlgaVT** [comment]
We could recommend trying both and warn that the results could be slightly different because the border PSI values of some events might pass the PSI value threshold calculated from one format and not pass from the other format.
